/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
static yyconst short int yy_accept[182] =
    {   0,
        0,    0,   22,   19,   20,   19,   19,   17,   17,   19,
       16,   16,    3,    3,   19,   17,   19,    2,   19,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,   17,   17,    0,   18,    0,    0,
        0,    7,    6,    4,    0,    0,    0,    3,    3,    3,
        2,   13,    2,    2,    2,    2,    2,    2,    1,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,   12,    0,    0,
        0,   10,    6,    0,    9,    4,    4,    0,    8,    5,
        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   14,    0,
        0,    0,    7,    0,    9,    0,    6,    4,   11,    5,
        5,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    0,   15,    0,    6,    5,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        8,    9,   10,    8,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    8,    8,   17,
       18,   19,   20,    1,   21,   21,   21,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   24,   24,
       24,   24,   24,   24,   26,   24,   24,   27,   24,   24,
        8,   28,    8,   29,   24,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   24,   39,   40,   41,   42,
       43,   44,   24,   45,   46,   47,   48,   49,   50,   51,
       52,   53,    8,   54,    8,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    4,    4,    4,    1,    1,    1,    2,
        4,    4,    4,    5,    5,    5,    5,    2,    1,    6,
        6,    4,    4,    4,    6,    5,    5,    5,    5,    5,
        5,    7,    5,    5,    7,    5,    7,    5,    7,    5,
        5,    5,    5,    1
    } ;

static yyconst short int yy_base[188] =
    {   0,
        0,    0,  372,  373,  373,  353,   51,  373,  364,  341,
      373,   42,   47,   87,   47,  350,   48,    0,    0,  319,
      321,   40,   37,   33,   42,  322,   51,  321,  329,   50,
      310,  319,  317,  322,  304,  373,   64,  373,  355,  349,
       75,  122,  149,  178,  108,  100,    0,    0,   51,   79,
        0,  373,  308,  320,  307,  322,  309,  315,  301,  302,
      299,  299,  302,  299,  296,    0,  295,  299,   58,  297,
       42,   87,  301,  294,   87,   68,  299,  373,  134,    0,
      144,  373,  213,  165,  373,  103,  106,  136,  182,  161,
      373,  293,  305,  300,  288,   93,  302,  300,  296,  288,

      294,  297,  283,  289,  286,  275,  277,  279,  286,  272,
      270,  270,  281,  269,  270,  274,  266,  245,  373,  154,
      277,  199,  209,  240,  373,  205,  243,  373,  373,  142,
      145,  243,  233,  241,  229,  236,  230,  227,  227,  227,
      223,  233,  222,  226,  231,  220,  213,  203,  207,  195,
      203,  226,  373,  225,  246,  373,  189,  190,  182,  169,
      163,  166,  173,  167,  167,  148,  154,  154,  136,  139,
      125,  119,  119,   99,   95,   78,   73,   51,   39,   26,
      373,  286,  293,  297,  303,  307,  310
    } ;

static yyconst short int yy_def[188] =
    {   0,
      181,    1,  181,  181,  181,  181,  182,  181,  181,  183,
      181,  181,  181,  181,  181,  181,  181,  184,  185,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  181,  181,  182,  181,  182,  181,
      181,  181,  181,  181,  181,  181,  186,   14,  181,  181,
      184,  181,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  181,  181,  187,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  186,
      181,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  181,  181,
      187,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  181,  181,  181,  181,  181,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
        0,  181,  181,  181,  181,  181,  181
    } ;

static yyconst short int yy_nxt[428] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,    8,    8,
        8,   12,    8,   13,   14,   14,   15,   16,   17,   11,
       18,   18,   18,   18,   18,   18,   18,   19,    8,   20,
       21,   22,   23,   24,   25,   26,   18,   27,   18,   28,
       18,   18,   18,   18,   29,   30,   31,   32,   33,   34,
       18,   18,   18,   35,   38,   42,   42,   42,   43,   66,
       44,   44,   45,   36,   36,   36,   36,   38,   46,   55,
       58,   66,   60,   47,   61,   91,   56,  108,   39,   59,
       46,   63,   57,   62,   64,   66,   70,   71,   79,   79,
       91,   39,   67,  105,  109,   66,   72,   47,   43,   73,

       48,   48,   48,   49,  106,  116,   66,  117,   46,   88,
       88,   49,   50,   89,   89,   89,  110,  180,   49,   43,
       46,   45,   45,   45,  114,   80,   49,  128,  179,   46,
       86,  111,  115,   66,   50,   42,   42,   42,  133,  134,
      119,   46,  128,   81,   82,   86,   82,  120,  120,   89,
       89,   89,  178,  122,  122,   81,   82,  123,  123,  123,
      119,   82,   83,   83,   83,   66,  156,  152,  152,  130,
       84,   85,  177,   85,  126,  126,  176,  175,  127,  127,
      127,  156,   84,   85,  130,  130,  131,  174,   85,   43,
       66,   44,   44,   45,   66,   89,   89,   89,   66,   46,

      130,   66,   86,   87,  129,   66,  129,   66,  131,  173,
       66,   46,  123,  123,  123,   66,  129,   86,  127,  127,
      127,  129,  123,  123,  123,   87,   83,   83,   83,  172,
      171,   82,  119,   82,  124,  125,   66,  125,  155,  155,
      155,  170,  169,   82,   66,  168,  124,  125,   82,  154,
      154,  167,  125,  155,  155,  155,  127,  127,  127,  155,
      155,  155,  166,  165,  164,   85,  163,   85,  125,   66,
      125,  162,  161,   66,  160,  159,  158,   85,  157,   66,
      125,   66,   85,  153,  151,  125,   37,   37,   37,   37,
       37,   37,   37,   40,   40,  150,   40,   40,   40,   40,

       51,   51,   51,   51,   52,   52,   66,  149,   52,   52,
       90,  148,   90,  121,  147,  121,  146,  145,  144,  143,
      142,  141,  140,  139,   66,   66,  138,  137,   66,   66,
      136,  135,   66,   66,  132,   66,  118,  113,  112,  107,
      104,   66,  103,   66,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   92,   78,  181,   36,   77,   76,
       75,   74,   69,   68,   65,   54,   53,   36,   41,   36,
       36,  181,    3,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,

      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181
    } ;

static yyconst short int yy_chk[428] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,   12,   12,   12,   13,  180,
       13,   13,   13,   15,   15,   17,   17,   37,   13,   22,
       23,  179,   24,   13,   24,   49,   22,   71,    7,   23,
       13,   25,   22,   24,   25,   27,   30,   30,   41,   41,
       49,   37,   27,   69,   71,  178,   30,   13,   14,   30,

       14,   14,   14,   50,   69,   76,  177,   76,   14,   46,
       46,   14,   14,   46,   46,   46,   72,  176,   50,   45,
       14,   45,   45,   45,   75,   41,   14,   86,  175,   45,
       87,   72,   75,  174,   14,   42,   42,   42,   96,   96,
       79,   45,   86,   42,   42,   87,   42,   79,   79,   88,
       88,   88,  173,   81,   81,   42,   42,   81,   81,   81,
      120,   42,   43,   43,   43,  172,  130,  120,  120,  131,
       43,   43,  171,   43,   84,   84,  170,  169,   84,   84,
       84,  130,   43,   43,  131,   90,   90,  168,   43,   44,
      167,   44,   44,   44,  166,   89,   89,   89,  165,   44,

       90,  164,   44,   44,   89,  163,   89,  162,   90,  161,
      160,   44,  122,  122,  122,  159,   89,   44,  126,  126,
      126,   89,  123,  123,  123,   44,   83,   83,   83,  158,
      157,  123,  152,  123,   83,   83,  151,   83,  154,  154,
      154,  150,  149,  123,  148,  147,   83,   83,  123,  124,
      124,  146,   83,  124,  124,  124,  127,  127,  127,  155,
      155,  155,  145,  144,  143,  127,  142,  127,  155,  141,
      155,  140,  139,  138,  137,  136,  135,  127,  134,  133,
      155,  132,  127,  121,  118,  155,  182,  182,  182,  182,
      182,  182,  182,  183,  183,  117,  183,  183,  183,  183,

      184,  184,  184,  184,  185,  185,  116,  115,  185,  185,
      186,  114,  186,  187,  113,  187,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   95,   94,   93,   92,   77,   74,   73,   70,
       68,   67,   65,   64,   63,   62,   61,   60,   59,   58,
       57,   56,   55,   54,   53,   40,   39,   35,   34,   33,
       32,   31,   29,   28,   26,   21,   20,   16,   10,    9,
        6,    3,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,

      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexioc.l"
#define INITIAL 0
#line 4 "lexioc.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// Definición de estructuras para listas enlazadas
typedef struct Nodo {
    void *dato;
    struct Nodo *siguiente;
} Nodo;

typedef struct {
    Nodo *cabeza;
} ListaEnlazada;

// Funciones para manejar listas enlazadas
Nodo* crearNodo(void *dato) {
    Nodo *nuevoNodo = (Nodo*)malloc(sizeof(Nodo));
    nuevoNodo->dato = dato;
    nuevoNodo->siguiente = NULL;
    return nuevoNodo;
}

ListaEnlazada* crearLista() {
    ListaEnlazada *lista = (ListaEnlazada*)malloc(sizeof(ListaEnlazada));
    lista->cabeza = NULL;
    return lista;
}

void agregar(ListaEnlazada *lista, void *dato) {
    Nodo *nuevoNodo = crearNodo(dato);
    nuevoNodo->siguiente = lista->cabeza;
    lista->cabeza = nuevoNodo;
}

// Estructuras para almacenar diferentes tipos de datos
typedef struct {
    char *identificador;
    int frecuencia;
} Identificador;

typedef struct {
    char *cadena;
    int longitud;
} LiteralCadena;

typedef struct {
    char *palabra;
    int linea;
    int columna;
} PalabraReservada;

typedef struct {
    int valor;
} ConstanteDecimal;

typedef struct {
    int valor;
} ConstanteHexadecimal;

typedef struct {
    int valor;
} ConstanteOctal;

typedef struct {
    double mantisa;
    int parteEntera;
} ConstanteReal;

typedef struct {
    char valor;
} ConstanteCaracter;

typedef struct {
    char operador;
    int frecuencia;
} Operador;

typedef struct {
    char *cadena;
    int linea;
    int columna;
} CadenaNoReconocida;

// Declaraciones de listas globales
ListaEnlazada *identificadores;
ListaEnlazada *literalesCadenas;
ListaEnlazada *palabrasReservadas;
ListaEnlazada *constantesDecimales;
ListaEnlazada *constantesHexadecimales;
ListaEnlazada *constantesOctales;
ListaEnlazada *constantesReales;
ListaEnlazada *constantesCaracteres;
ListaEnlazada *operadores;
ListaEnlazada *cadenasNoReconocidas;

// Inicialización de listas
void inicializarListas() {
    identificadores = crearLista();
    literalesCadenas = crearLista();
    palabrasReservadas = crearLista();
    constantesDecimales = crearLista();
    constantesHexadecimales = crearLista();
    constantesOctales = crearLista();
    constantesReales = crearLista();
    constantesCaracteres = crearLista();
    operadores = crearLista();
    cadenasNoReconocidas = crearLista();
}

// Funciones para agregar datos a las listas enlazadas correspondientes
void agregarIdentificador(char *identificador) {
    Nodo *actual = identificadores->cabeza;
    while (actual != NULL) {
        Identificador *id = (Identificador*)actual->dato;
        if (strcmp(id->identificador, identificador) == 0) {
            id->frecuencia++;
            return;
        }
        actual = actual->siguiente;
    }
    Identificador *nuevoId = (Identificador*)malloc(sizeof(Identificador));
    nuevoId->identificador = strdup(identificador);
    nuevoId->frecuencia = 1;
    agregar(identificadores, nuevoId);
}

void agregarLiteralCadena(char *cadena) {
    LiteralCadena *literal = (LiteralCadena*)malloc(sizeof(LiteralCadena));
    literal->cadena = strdup(cadena);
    literal->longitud = strlen(cadena);
    agregar(literalesCadenas, literal);
}

void agregarPalabraReservada(char *palabra, int linea, int columna) {
    PalabraReservada *reservada = (PalabraReservada*)malloc(sizeof(PalabraReservada));
    reservada->palabra = strdup(palabra);
    reservada->linea = linea;
    reservada->columna = columna;
    agregar(palabrasReservadas, reservada);
}

void agregarConstanteDecimal(int valor) {
    ConstanteDecimal *constante = (ConstanteDecimal*)malloc(sizeof(ConstanteDecimal));
    constante->valor = valor;
    agregar(constantesDecimales, constante);
}

void agregarConstanteHexadecimal(int valor) {
    ConstanteHexadecimal *constante = (ConstanteHexadecimal*)malloc(sizeof(ConstanteHexadecimal));
    constante->valor = valor;
    agregar(constantesHexadecimales, constante);
}

void agregarConstanteOctal(int valor) {
    ConstanteOctal *constante = (ConstanteOctal*)malloc(sizeof(ConstanteOctal));
    constante->valor = valor;
    agregar(constantesOctales, constante);
}

void agregarConstanteReal(double mantisa, int parteEntera) {
    ConstanteReal *constante = (ConstanteReal*)malloc(sizeof(ConstanteReal));
    constante->mantisa = mantisa;
    constante->parteEntera = parteEntera;
    agregar(constantesReales, constante);
}

void agregarConstanteCaracter(char valor) {
    ConstanteCaracter *constante = (ConstanteCaracter*)malloc(sizeof(ConstanteCaracter));
    constante->valor = valor;
    agregar(constantesCaracteres, constante);
}

void agregarOperador(char operador) {
    Nodo *actual = operadores->cabeza;
    while (actual != NULL) {
        Operador *op = (Operador*)actual->dato;
        if (op->operador == operador) {
            op->frecuencia++;
            return;
        }
        actual = actual->siguiente;
    }
    Operador *nuevoOp = (Operador*)malloc(sizeof(Operador));
    nuevoOp->operador = operador;
    nuevoOp->frecuencia = 1;
    agregar(operadores, nuevoOp);
}

void agregarCadenaNoReconocida(char *cadena, int linea, int columna) {
    CadenaNoReconocida *noReconocida = (CadenaNoReconocida*)malloc(sizeof(CadenaNoReconocida));
    noReconocida->cadena = strdup(cadena);
    noReconocida->linea = linea;
    noReconocida->columna = columna;
    agregar(cadenasNoReconocidas, noReconocida);
}

// Variables para seguimiento de líneas y columnas
int linea = 1;
int columna = 1;

// Función para imprimir los listados
void imprimirListados() {
    printf("* Listado de identificadores encontrados:\n");
    Nodo *actual = identificadores->cabeza;
    while (actual != NULL) {
        Identificador *id = (Identificador*)actual->dato;
        printf("%s: aparece %d veces\n", id->identificador, id->frecuencia);
        actual = actual->siguiente;
    }

    printf("\n* Listado de literales cadena encontrados:\n");
    actual = literalesCadenas->cabeza;
    while (actual != NULL) {
        LiteralCadena *literal = (LiteralCadena*)actual->dato;
        printf("\"%s\": longitud %d\n", literal->cadena, literal->longitud);
        actual = actual->siguiente;
    }

    printf("\n* Listado de palabras reservadas (tipos de dato):\n");
    actual = palabrasReservadas->cabeza;
    while (actual != NULL) {
        PalabraReservada *reservada = (PalabraReservada*)actual->dato;
        if (strcmp(reservada->palabra, "int") == 0 || strcmp(reservada->palabra, "void") == 0 || strcmp(reservada->palabra, "char") == 0) {
            printf("%s: linea %d, columna %d\n", reservada->palabra, reservada->linea, reservada->columna);
        }
        actual = actual->siguiente;
    }

    printf("\n* Listado de palabras reservadas (estructuras de control):\n");
    actual = palabrasReservadas->cabeza;
    while (actual != NULL) {
        PalabraReservada *reservada = (PalabraReservada*)actual->dato;
        if (strcmp(reservada->palabra, "if") == 0 || strcmp(reservada->palabra, "else") == 0 || strcmp(reservada->palabra, "while") == 0 ||
            strcmp(reservada->palabra, "for") == 0 || strcmp(reservada->palabra, "return") == 0) {
            printf("%s: linea %d, columna %d\n", reservada->palabra, reservada->linea, reservada->columna);
        }
        actual = actual->siguiente;
    }

    printf("\n* Listado de palabras reservadas (otros):\n");
    actual = palabrasReservadas->cabeza;
    while (actual != NULL) {
        PalabraReservada *reservada = (PalabraReservada*)actual->dato;
        if (strcmp(reservada->palabra, "sizeof") == 0) {
            printf("%s: linea %d, columna %d\n", reservada->palabra, reservada->linea, reservada->columna);
        }
        actual = actual->siguiente;
    }

    printf("\n* Listado de constantes enteras decimales:\n");
    int totalDecimales = 0;
    actual = constantesDecimales->cabeza;
    while (actual != NULL) {
        ConstanteDecimal *decimal = (ConstanteDecimal*)actual->dato;
        printf("%d: valor %d\n", decimal->valor, decimal->valor);
        totalDecimales += decimal->valor;
        actual = actual->siguiente;
    }
    printf("Total acumulado de sumar todas las constantes decimales: %d\n", totalDecimales);

    printf("\n* Listado de constantes enteras hexadecimales:\n");
    actual = constantesHexadecimales->cabeza;
    while (actual != NULL) {
        ConstanteHexadecimal *hexa = (ConstanteHexadecimal*)actual->dato;
        printf("%X: valor entero decimal %d\n", hexa->valor, hexa->valor);
        actual = actual->siguiente;
    }

    printf("\n* Listado de constantes enteras octales:\n");
    actual = constantesOctales->cabeza;
    while (actual != NULL) {
        ConstanteOctal *octal = (ConstanteOctal*)actual->dato;
        printf("%o: valor entero decimal %d\n", octal->valor, octal->valor);
        actual = actual->siguiente;
    }

    printf("\n* Listado de constantes reales:\n");
    actual = constantesReales->cabeza;
    while (actual != NULL) {
        ConstanteReal *real = (ConstanteReal*)actual->dato;
        printf("%lf: parte entera %lf , mantisa %lf\n", real->mantisa + real->parteEntera, (double)real->parteEntera, real->mantisa);
        actual = actual->siguiente;
    }

    printf("\n* Listado de constantes caracter enumerados:\n");
    int contadorCaracteres = 1;
    actual = constantesCaracteres->cabeza;
    while (actual != NULL) {
        ConstanteCaracter *caracter = (ConstanteCaracter*)actual->dato;
        printf("%d) '%c'\n", contadorCaracteres, caracter->valor);
        contadorCaracteres++;
        actual = actual->siguiente;
    }

    // Imprimir operadores
    printf("\n* Listado de operadores/caracteres de puntuación:\n");
    actual = operadores->cabeza;
    while (actual != NULL) {
        Operador *op = (Operador*)actual->dato;
        printf("%c: aparece %d veces\n", op->operador, op->frecuencia);
        actual = actual->siguiente;
    }

    // Imprimir cadenas no reconocidas
    printf("\n* Listado de cadenas no reconocidas:\n");
    actual = cadenasNoReconocidas->cabeza;
    while (actual != NULL) {
        CadenaNoReconocida *noReconocida = (CadenaNoReconocida*)actual->dato;
        printf("%s: linea %d, columna %d\n", noReconocida->cadena, noReconocida->linea, noReconocida->columna);
        actual = actual->siguiente;
    }
}
#line 834 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 319 "lexioc.l"


#line 988 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 182 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 373 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 321 "lexioc.l"
{
    agregarPalabraReservada(yytext, linea, columna);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 325 "lexioc.l"
{
    agregarIdentificador(yytext);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 329 "lexioc.l"
{
    int valor = atoi(yytext);
    agregarConstanteDecimal(valor);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 334 "lexioc.l"
{
    int valor = strtol(yytext, NULL, 8);
    agregarConstanteOctal(valor);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 339 "lexioc.l"
{
    int valor = strtol(yytext, NULL, 16);
    agregarConstanteHexadecimal(valor);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 344 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 349 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 354 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 359 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 364 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 369 "lexioc.l"
{
    double valor = atof(yytext);
    agregarConstanteReal(modf(valor, &valor), (int)valor);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 374 "lexioc.l"
{
    agregarConstanteCaracter(yytext[1]);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 378 "lexioc.l"
{
    agregarConstanteCaracter(yytext[1]);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 382 "lexioc.l"
{
    int valor = strtol(yytext+1, NULL, 8);
    agregarConstanteCaracter(valor);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 387 "lexioc.l"
{
    int valor = strtol(yytext+2, NULL, 16);
    agregarConstanteCaracter(valor);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 392 "lexioc.l"
{
    agregarOperador(yytext[0]);
    columna = columna + yyleng;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 397 "lexioc.l"
{
    agregarOperador(yytext[0]);
    columna = columna + yyleng;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 403 "lexioc.l"
{
    agregarLiteralCadena(yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 407 "lexioc.l"
{
    agregarCadenaNoReconocida(yytext, linea, columna);
    columna++;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 413 "lexioc.l"
{
    linea++;
    columna = 1;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 419 "lexioc.l"
ECHO;
	YY_BREAK
#line 1231 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 182 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 182 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 181);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 419 "lexioc.l"


int main(int argc, char* argv[]) {
    inicializarListas();
    yylex();
    imprimirListados();
    return 0;
}


